# Нейронные сети

https://stepik.org/course/401

# _Задачи_

## 1. Основы линейной алгебры

### 1.7. Линейная алгебра в деле

#### 1.7.1

`?`

Теперь давайте попробуем применить наши новые матричные формулы — сначала на игрушечном примере, который мы рассматривали пару видео назад.

У нас есть набор данных: знания о длине тормозного пути и скорости для трёх автомобилей.

\begin{pmatrix} D & V \\ \hline 10 & 60 \\ 7 & 50 \\ 12 & 75\end{pmatrix}

 
Напишите через запятую оценки коэффициентов линейной регрессии D на V, т.е. \hat{\beta}_0, \hat{\beta}_1 для модели D=\beta_0+\beta_1 V+\varepsilonD=β V+ε с точностью до трёх знаков после точки.


In [1]:
import numpy as np

In [2]:
def add_beta_zero(B):
    '''добавление единичного столбца для вычисления бета нулевого'''
    return np.hstack([np.ones((len(B), 1)), B])

def get_betas(X, Y):
    '''(x.T * x) ^ -1 * x.T * y'''
    return np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ Y)

In [3]:
d = [10, 7, 12]
v = [60, 50, 75]

In [4]:
D = np.array(d).reshape(-1, 1)
D

array([[10],
       [ 7],
       [12]])

In [5]:
V = np.array(v).reshape(-1, 1)
V

array([[60],
       [50],
       [75]])

добавим в V единичный столбец для вычисления бета нулевого

In [6]:
V = add_beta_zero(V)
V

array([[ 1., 60.],
       [ 1., 50.],
       [ 1., 75.]])

In [7]:
B = get_betas(V, D)
B

array([[-2.34210526],
       [ 0.19473684]])

In [8]:
b0 = round(B[0][0], 3)
b0

-2.342

In [9]:
b1 = round(B[1][0], 3)
b1

0.195

In [10]:
result = f'{b0}, {b1}'
result

'-2.342, 0.195'