# Нейронные сети

https://stepik.org/course/401

# _Задачи_

## 1. Основы линейной алгебры

### 1.7. Линейная алгебра в деле

#### 1.7.1

`?`

Теперь давайте попробуем применить наши новые матричные формулы — сначала на игрушечном примере, который мы рассматривали пару видео назад.

У нас есть набор данных: знания о длине тормозного пути и скорости для трёх автомобилей.

\begin{pmatrix} D & V \\ \hline 10 & 60 \\ 7 & 50 \\ 12 & 75\end{pmatrix}

 
Напишите через запятую оценки коэффициентов линейной регрессии D на V, т.е. \hat{\beta}_0, \hat{\beta}_1 для модели D=\beta_0+\beta_1 V+\varepsilonD=β V+ε с точностью до трёх знаков после точки.


In [1]:
import numpy as np

In [2]:
def add_beta_zero(B):
    '''добавление единичного столбца для вычисления бета нулевого'''
    return np.hstack([np.ones((len(B), 1)), B])

def get_betas(X, Y):
    '''(x.T * x) ^ -1 * x.T * y'''
    return np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ Y)

In [3]:
d = [10, 7, 12]
v = [60, 50, 75]

In [4]:
D = np.array(d).reshape(-1, 1)
D

array([[10],
       [ 7],
       [12]])

In [5]:
V = np.array(v).reshape(-1, 1)
V

array([[60],
       [50],
       [75]])

добавим в V единичный столбец для вычисления бета нулевого

In [6]:
V = add_beta_zero(V)
V

array([[ 1., 60.],
       [ 1., 50.],
       [ 1., 75.]])

In [7]:
B = get_betas(V, D)
B

array([[-2.34210526],
       [ 0.19473684]])

In [8]:
b0 = round(B[0][0], 3)
b0

-2.342

In [9]:
b1 = round(B[1][0], 3)
b1

0.195

In [10]:
result = f'{b0}, {b1}'
result

'-2.342, 0.195'

#### 1.7.2

`>_`

Найдите оптимальные коэффициенты для построения линейной регрессии.

На вход вашему решению будет подано название csv-файла, из которого нужно считать данные. Пример можно посмотреть [здесь](https://stepik.org/media/attachments/lesson/16462/boston_houses.csv). Загрузить их можно следующим образом:
```
fname = input()  # read file name from stdin
f = urllib.request.urlopen(fname)  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with
```

Ваша задача — подсчитать вектор коэффициентов линейной регрессии для предсказания первой переменной (первого столбца данных) по всем остальным. Напомним, что модель линейной регрессии — это y = β0 + β1 x1 + ... + βn xn 


Напечатайте коэффициенты линейной регрессии, начиная с β0, через пробел. Мы будем проверять совпадения с точностью до 4 знаков после запятой.

Методы и приёмы, которые мы ещё не упоминали и которые могут вам помочь в процессе решения (могут являться подсказками!):
```
np.hstack((array1, array2, ...))  # склеивает по строкам массивы, являющиеся компонентами кортежа, поданного на вход; массивы должны совпадать по всем измерениям, кроме второго
np.ones_like(array)  # создаёт массив, состоящий из единиц, идентичный по форме массиву array
"delim".join(array)  # возвращает строку, состоящую из элементов array, разделённых символами "delim"
map(str, array)  # применяет функцию str к каждому элементу array
```


In [11]:
from urllib import request

#fname = input()  # read file name from stdin
fname = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'

f = request.urlopen(fname)
data = np.loadtxt(f, delimiter=',', skiprows=1)

In [12]:
Y = data[:, 0].reshape(-1, 1)

In [13]:
Y.T

array([[24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 

In [14]:
X = data[:, 1:]
X = add_beta_zero(X)

In [15]:
X

array([[1.0000e+00, 6.3200e-03, 1.8000e+01, ..., 5.3800e-01, 6.5750e+00,
        4.0900e+00],
       [1.0000e+00, 2.7310e-02, 0.0000e+00, ..., 4.6900e-01, 6.4210e+00,
        4.9671e+00],
       [1.0000e+00, 2.7290e-02, 0.0000e+00, ..., 4.6900e-01, 7.1850e+00,
        4.9671e+00],
       ...,
       [1.0000e+00, 6.0760e-02, 0.0000e+00, ..., 5.7300e-01, 6.9760e+00,
        2.1675e+00],
       [1.0000e+00, 1.0959e-01, 0.0000e+00, ..., 5.7300e-01, 6.7940e+00,
        2.3889e+00],
       [1.0000e+00, 4.7410e-02, 0.0000e+00, ..., 5.7300e-01, 6.0300e+00,
        2.5050e+00]])

In [16]:
B = get_betas(X, Y)

In [17]:
B

array([[ -3.65580429],
       [ -0.2163955 ],
       [  0.0737306 ],
       [  4.41245058],
       [-25.46844878],
       [  7.14320155],
       [ -1.30108768]])

In [18]:
result = ' '.join(map(str, map(lambda x: round(x[0], 4), B)))

In [19]:
result

'-3.6558 -0.2164 0.0737 4.4125 -25.4684 7.1432 -1.3011'

итоговый код:

In [20]:
import numpy as np
from urllib import request


def add_beta_zero(B):
    return np.hstack([np.ones((len(B), 1)), B])

def get_betas(X, Y):
    return np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ Y)


#fname = input()
fname = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'

f = request.urlopen(fname)
data = np.loadtxt(f, delimiter=',', skiprows=1)

Y = data[:, 0].reshape(-1, 1)
X = add_beta_zero(data[:, 1:])
B = get_betas(X, Y)
result = ' '.join(map(str, map(lambda x: round(x[0], 4), B)))
print(result)

-3.6558 -0.2164 0.0737 4.4125 -25.4684 7.1432 -1.3011
